# Generated by Django 5.2.16 on 2026-07-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated_at', models.DateTimeField()),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['category', 'price'], name='items_category_price_idx'), models.Index(fields=['price'], name='items_price_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='items_item_source_external_id_uniq'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='items_item_price_nonnegative')],
            },
        ),
    ]
